### ISSUE TITLE
Conversion routines between PJCL and ECMAScript2020 BigInt encodings would be useful

### ISSUE THREAD

**Issue by fcorella** [fcorella/pjcl#2]
As I said in a [comment on issue 1](https://github.com/fcorella/pjcl/issues/1), PJCL predates ECMAScript2020 and does not use the JavaScript BigInt type, encoding big integers instead as arrays of 24-bit limbs.  It would be nice to add functions to the library for converting between the two encodings, such as a function pjclBigInt_to_ESBigInt for converting from the PJCL encoding to the ES 2020 endoing and a function pjclBigInt_from_ESBigInt for converting from the ES encoding to the PJCL encoding.

**Comment by James-E-A** [comment]
This would look something like the following (performance notwithstanding (though I think this should be *close to* optimal)):

```js
function pjclBigInt_from_ES11BigInt(i) {
	const shift = BigInt(pjclBaseBitLength), mask = BigInt(pjclBaseMask);

	var x = [];
	if (i < 0) {
		x.negative = true;
		i = -i;
	}
	while (i) {
		x.push(Number(i & mask));
		i >>= shift;
	}

	return x;
}


function pjclBigInt_to_ES11BigInt(x) {
	const shift = BigInt(pjclBaseBitLength);

	var i = BigInt(0), j = x.length;
	while (j--) {
		i <<= shift;
		i += BigInt(x[j]);
	}
	if (x.negative) {
		i = -i;
	}

	return i;
}
```

**Comment by James-E-A** [comment]
How _should_ negative ES6 BigInts be handled?

**Comment by fcorella** [comment]
Thank you, James, this is very good.  Would you like to create a pull request for it?

**Comment by James-E-A** [comment]
I'll do that this evening -- though before I sent in a PR I was wondering whether you want to expose any **automatic** interfacing with ES11 BigInts?

Or should wrapping and unwrapping be left up to the caller to do manually, to avoid unintentionally promoting severely inefficient usage of the library?

**Comment by fcorella** [comment]
By automatic interfacing I suppose you mean that certain library functions would check whether their big integer arguments are encoded as ES11 BigInts.  If so they would convert those arguments to pjcl big integers, and set an internal flag, which would cause their big integer results to be converted to ES11 BigInts.  That's an excellent idea. 

Doing that for basic arithmetic functions such as pjclAdd, might result in that function being used instead of ES11 BigInt addition inside an inner loop, which would be the kind of severely inefficient usage of the library that you are thinking about.  But it could be done in top-tier functions that implement cryptographic primitives such as ECDSA or Diffie-Hellman.  We will have to figure out which functions should be in the top tier, and how to document it.
